// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhad4M1QnoM9AMLBsC3cDIzsv1Cn2_LvA',
    appId: '1:473848806984:web:e516737b31001f76d1227d',
    messagingSenderId: '473848806984',
    projectId: 'buzz-bb368',
    authDomain: 'buzz-bb368.firebaseapp.com',
    storageBucket: 'buzz-bb368.appspot.com',
    measurementId: 'G-9LC7X7QQJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRHgHQJ_PP9RRXgZufDjQb2m5Lo9kJkA',
    appId: '1:473848806984:android:b35962b602dde8c8d1227d',
    messagingSenderId: '473848806984',
    projectId: 'buzz-bb368',
    storageBucket: 'buzz-bb368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXXQYGrxWie22ah0g2mfab4FphqOTomg',
    appId: '1:473848806984:ios:0b774b1703369cafd1227d',
    messagingSenderId: '473848806984',
    projectId: 'buzz-bb368',
    storageBucket: 'buzz-bb368.appspot.com',
    iosBundleId: 'com.dshreddy.buzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkXXQYGrxWie22ah0g2mfab4FphqOTomg',
    appId: '1:473848806984:ios:c853f3ae6ee123b5d1227d',
    messagingSenderId: '473848806984',
    projectId: 'buzz-bb368',
    storageBucket: 'buzz-bb368.appspot.com',
    iosBundleId: 'com.example.buzz.RunnerTests',
  );
}
